FROM dart:stable

ENV DART_VM_OPTIONS="--old_gen_heap_size=256"
ENV PUB_CACHE=/tmp/pub_cache

WORKDIR /app
COPY . /app
WORKDIR /app/backend

CMD ["bash","-lc","dart pub get && dart analyze && dart test"]
